BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Settings";
CREATE TABLE IF NOT EXISTS "Settings" (
	"SettingId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Key"	TEXT NOT NULL UNIQUE,
	"Value"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "TelegramUsers";
CREATE TABLE IF NOT EXISTS "TelegramUsers" (
	"UserId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"ChatId"	INTEGER NOT NULL UNIQUE,
	"FirstName"	TEXT,
	"LastName"	TEXT,
	"UserName"	TEXT,
	"DateRegisteredUtc"	TEXT NOT NULL,
	"UserIsSubscribed"	INTEGER NOT NULL,
	"UserIsAdmin"	INTEGER NOT NULL,
	"UserLocationLatitude"	REAL,
	"UserLocationLongitude"	REAL
);
INSERT INTO "Settings" VALUES (1,'DB_VERSION','7');
COMMIT;
