BEGIN TRANSACTION;
DROP TABLE IF EXISTS "Settings";
CREATE TABLE IF NOT EXISTS "Settings" (
	"SettingId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"Key"	TEXT NOT NULL UNIQUE,
	"Value"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "TelegramUsers";
CREATE TABLE IF NOT EXISTS "TelegramUsers" (
	"UserId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"ChatId"	INTEGER NOT NULL UNIQUE,
	"FirstName"	TEXT NOT NULL,
	"LastName"	TEXT NOT NULL,
	"UserName"	TEXT NOT NULL,
	"DateRegisteredUtc"	TEXT NOT NULL,
	"UserIsSubscribed"	TEXT NOT NULL,
    "UserIsAdmin"	TEXT NOT NULL
);
DROP TABLE IF EXISTS "CoronaCaseDistributionRecords";
CREATE TABLE IF NOT EXISTS "CoronaCaseDistributionRecords" (
    "CaseId"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
    "DateCollectedUtc"	TEXT NOT NULL,
    "CaseDistributionRecords"	TEXT NOT NULL
);
INSERT INTO "Settings" VALUES (1,'DB_VERSION','3');
COMMIT;
